#!/bin/bash
set -x
outfile=out.mpg
flist=flist.txt
function usage() {
	echo "Usage: $0 [-o output.mpg] input.mpg tIni tEnd"
}
fname=`basename $1 .jpg`

if [ "$#" -lt "2" ]; then
	usage
	echo "Usage: [-o output.mpg] in1.mpg in2.mpg ... inN.mpg"
	exit
fi
while [ "$#" -gt "0" ]; do
	echo "option:$1"
	case $1 in
	    "-o")
		shift
		outfile=$1
		echo "outfile=$outfile"
		;;
	    "-h")
		usage
		exit
		;;
	    *)
		break 
	esac
	shift
done
echo "saiu do primerio"

ffmpeg -i $1 -c copy -t $2 $1_p1.mp4 
ffmpeg -ss $3 -i $1 -c copy $1_p2.mp4
echo "criou"
echo "# input file list" >$flist
echo "# List created by vtCut, from VideoTools." >> $flist
echo "# https://github.com/miguelleitao/VideoTools" >> $flist
echo "# Output file: $outfile" >>$flist

echo "file $1_p1.mp4" >> $flist
echo "file $1_p2.mp4" >> $flist
cat $flist
ffmpeg -f concat -i $flist -c copy $outfile

